### PR TITLE
Bug Fix #7: Favicon added and Readme file corrected

### LINKED ISSUE #7: Add a favicon to the site
We must add a favicon to the site for display in the title bar

### PR DESCRIPTION
**Pull request by gagandeepp**

### CODE REVIEW

**Comment by gagandeepp** [comment]
@jlengstorf  Please review and merge this

**Review by DSchau — CHANGES_REQUESTED** [review]
Can we revert the changes to readme?

**Review by DSchau — CHANGES_REQUESTED** [review]
Also missing a space in the link tag!

**Review by DSchau — APPROVED** [review]
Thanks!

**Comment by gagandeepp** [comment]
@DSchau Code Pointers Implemented

**Pull request merged**
